### ISSUE TITLE
Error with Nollup, not with Rollup 2

### ISSUE THREAD

**Issue by frederikhors** [rixo/rollup-plugin-svelte-hot#12]
Here we are with a small reproduction for a new error with Nollup only: https://github.com/frederikhors/svelte-template-hot/tree/use-events-current-component-nollup.

A small Button component which is trying to use this code: https://github.com/vikignt/svelte-mui/blob/master/src/lib/events.js.

Works with Rollup, NOT with Nollup. Error:

`TypeError: Cannot read property '$$' of undefined`

**Comment by rixo** [comment]
Same as the previous one, `current_component` from `svelte/internal` is a live binding, so not supported by Nollup.

You can use `get_current_component` (i.e. `import { get_current_component } from "svelte/internal"`) instead, if you want to stay in the business of using forbidden private APIs things...

Closing, not fixable from here.

**Comment by frederikhors** [comment]
> if you want to stay in the business of using forbidden private APIs things...

LOL.

Can I ask you more about live bindings?

**Comment by rixo** [comment]
Live bindings are a feature of ES module system (i.e. `import`). You can export a `let` variable and when its value changes in the exporting module then the new value is visible by importing modules (don't think you can change it from importers, but I'm not 100% sure).

`a.js`

```js
export let a = 0

setInterval(() => {
  a++
}, 1000})
```

```js
import { a } from './a.js'

setInterval(() => {
  console.log(a)
}, 500)
```

Will log:

```
0
1
1
2
2
...
```

See the idea?

Nollup doesn't implement that currently.
