### ISSUE TITLE
npm run dev:rollup doesn't work over the network

### ISSUE THREAD

**Issue by jacob-8** [rixo/rollup-plugin-svelte-hot#6]
Problem: Can't use on another device over the network.

Steps to reproduce:
1. `git clone https://github.com/jwrunner/athletic-line-chart.git`
2. `npm run dev:rollup` - note that I set the host to 0.0.0.0
3. Try to open on another device on the network. The page hangs for a long time on a blank white screen. Upon inspection, you can see the page source came across the wire properly, but the page spinner continues for a long time. Eventually it runs out of breath with the error: "GET http://192.168.0.2:38670/runtime/hmr-runtime.js net::ERR_CONNECTION_TIMED_OUT"

For reference, the my computer is serving the page at 192.168.0.2:5000 and in my terminal upon startup I also see:
[HMR] Listening on port 38670
[HMR] Serving from RAM at http://127.0.0.1:38670"

**Comment by rixo** [comment]
The HMR plugin is spinning it's own web server, beside your normal one (sirv), to serve HMR modules from RAM.

You need to set host `0.0.0.0` there too:

~~~js
    hmr({
      host: '0.0.0.0', // <---
      public: 'public',
      inMemory: true,
      ...
    }),
~~~

**Comment by jacob-8** [comment]
Great, thanks! Consider including that in your template or instructions, at least commented out. Developing quickly using multiple devices over the network is one of the most compelling parts of the DX here.

**Comment by rixo** [comment]
You're not the first one mentioning this.

I've added a mention to the option to the template's config: https://github.com/rixo/svelte-template-hot/blob/87b04d65cbc739278bcdb476dcd8fbc99da820a1/rollup.config.js#L92.

Thanks for your feedback.
