### ISSUE TITLE
Exported Property Value Not Updating

### ISSUE THREAD

**Issue by robots4life** [rixo/rollup-plugin-svelte-hot#7]
Not sure if this is supposed to be happening of if this has to do with this issue. [https://github.com/rixo/svelte-template-hot/issues/1](https://github.com/rixo/svelte-template-hot/issues/1)

The rollup.config.js looks like this.
[rollup.config.txt](https://github.com/rixo/rollup-plugin-svelte-hot/files/4813081/rollup.config.txt)

In `src` I have Title.svelte
```
<script>
	export let title = 'default title';
</script>

<div class="main-title">
	<h2>{title}</h2>
</div>
```
and App.svelte.
```
<script>
	import Title from './Title.svelte';
</script>

<Title title="another title" />

<Title />
```
Now when I run `npm run dev:rollup` I can see the page fine under `http://172.16.238.10:5000/`.

However when I change the variable `title` from `default title` to `another longer title` and save the changes, the page does not change the value of the Title component where the property value is not given.

The 1st instance of the Title component works as expected, however the 2nd instance only updates the value of the `title` variable given in Title.svelte if I reload the entire page.

Is this due to the settings I have chosen in `rollup.config.js` or is it something else?

This is my package.json file. Should have all the right versions.
[package.json.txt](https://github.com/rixo/rollup-plugin-svelte-hot/files/4813122/package.json.txt)

**Comment by rixo** [comment]
Thanks for the feedback!

I think you're witnessing preservation of local state in action here...

When you change `export let title` in `Title.svelte`, every instance of `Title` will be recreated and state is transferred from existing instances (being destroyed) to the new ones. In this preserved state, there is the value of `title` as `'default title'`. The new default is not applied, since we already have a value.

If you change to `noPreserveState: true`, you shouldn't see this anymore.

Alternatively, when you change the default value of the title prop, you can add a `// @!hmr` comment in your component's source to disable preservation of state for this HMR update:

~~~svelte
<script>
  export let title = 'new title' // @!hmr
  ...
</script>
...
~~~

Preservation of local state can be confusing unfortunately :-/ Maybe it should be disabled by default?

**Comment by robots4life** [comment]
Thank you indeed for your swift reply. No, regardless of the issue I am having, it is good to have preservation of local state by default and just make it clear in the docs or [readme](https://github.com/rixo/rollup-plugin-svelte-hot/blob/master/README.md) what is going on. And yes you are right, it might be confusing at first but this is what your repo is about, HMR and keeping local state of the components. I would not change the defaults, perhaps just add more info about it.

To my issue. And I was so happy to think that this had to do with seeing HMR in action.. however what I am seeing is the following behavior.

Regardless of what options I use `noPreserveState: true` or the special `// @!hmr` comment in the `Title.svelte` component, as long as I hit save in `Title.svelte` the change in the default value is not applied unfortunately.

However, when I hit save in `App.svelte` the change for the Title component is immediately applied and the default value is changed according to what I have it in `Title.svelte`. Again, this happens regardless of any changes in options or if I am using the special comment. In both cases, the changes are only applied when I hit save in `App.svelte`.

Checked Dev Tools and made sure to disable cache just in case. Given your feedback I might have [something wrong with my setup](https://github.com/cytopia/devilbox/issues/709). On it.

At the moment I am trying to get the default svelte-template as well as your [svelte-template-hot](https://github.com/rixo/svelte-template-hot) with your [rollup-plugin-svelte-hot](https://github.com/rixo/rollup-plugin-svelte-hot) going on a secure local dev domain.

Though regardless of those issues, the above mentioned behavior persists even on the Node generated server under `http://172.16.238.10:5000/`. This also happens on `http://127.0.0.1:5001/`. Happy to document more of this as soon as I find a solution. If you have a clue, I am all ears. :ear: :thinking:

**Comment by rixo** [comment]
> Regardless of what options I use noPreserveState: true or the special // @!hmr comment in the Title.svelte component, as long as I hit save in Title.svelte the change in the default value is not applied unfortunately.

Yeah, the behaviour was actually not possible to disable for props (i.e. exported `let`). I had overlooked this.

I think it doesn't make a lot of sense to differentiate between props & local variables for that, so I've changed / fixed it in `0.10.0-0` (`npm install -D rollup-plugin-svelte-hot@next`).

Good catch, thanks. Hope you didn't lose too much time on this :-x Can you confirm it works better for you with `next` version?

> And yes you are right, it might be confusing at first but this is what your repo is about, HMR and keeping local state of the components.

You still get a lot of benefits from HMR, even when local state is not preserved:

- the state of all the rest of the app is preserved (it's just all branches of the components tree starting at a node with the updated component that are reset)

- saving the time of a full browser reload (which can run anywhere from 200ms to >1s with no-bundler dev servers like Vite), which essentially closes the gap to a barely perceptible feedback delay

Also, you always get a part of the state that is preserved because it is fed through props to the updated component by its parent.

I'm really split on the right default for this option, but I've decided to keep it like it is for now. Most of the time the feature is useful, and I think it makes it more discoverable. If it annoys people, they will search how to turn it off, whether if it is not here they might not think of it or think it is not supported...

I've documented the behaviour [in svelte-hmr](https://github.com/rixo/svelte-hmr#preservation-of-local-state) for now. I'd appreciate your feedback, if you have the time. I think I'm going to link the HMR explanation from this plugin.

**Comment by robots4life** [comment]
Just a tiny FYI. I managed to resolve the [mentioned issue](https://github.com/cytopia/devilbox/issues/709) and am coming back to testing HMR with your plugin. Will report back in any case with what I found. Great you already did document this, thank you.

**Comment by robots4life** [comment]
What I thought would be a solution was not quite right. However I learned more about it and fixed that as well.

Here is a Svelte template working with Devilbox and LiveReload on a secure local development domain. https://github.com/robots4life/svelte-slr

I am now venturing into [your hot plugin](https://github.com/rixo/rollup-plugin-svelte-hot/) in combination with [your hot template](https://github.com/rixo/rollup-plugin-svelte-hot) and will see how I can get that to work on a secure local development domain as well and will report back with any news about this.

**Comment by rixo** [comment]
Going well? Should we keep this open?

**Comment by robots4life** [comment]
On it today, expect feedback soon, thank you for asking.

**Comment by robots4life** [comment]
With https://github.com/rixo/svelte-hmr#preservation-of-local-state and

```
npm install -D rollup-plugin-svelte-hot@next
```

and 

```
noPreserveState: false,
```

or

```
noPreserveState: true,
```

it works as expected. :100: Thank you. As far as this issue is concerned this ticket is resolved on localhost and that works for most cases.

Perhaps you have an idea why the following is happening when not on localhost?

![Screenshot_20200828_113412](https://user-images.githubusercontent.com/34193243/91546561-ec400580-e922-11ea-8419-fea0e3db9289.png)

![Screenshot_20200828_113546](https://user-images.githubusercontent.com/34193243/91546698-24dfdf00-e923-11ea-976c-6bac81f9d839.png)

In both cases I am just swapping out values with `noPreserveState` either set to `true` or `false` and saving. Running `npm run dev` and starting the HMR server with Nollup however does only work on localhost. However when I try the same on a secure local domain the `_hmr` server cannot be found. 

The LiveReload port `35729` as well as the HMR port `33440` are passed through, works with LIveReload so the ports should not be an issue.

Svelte runs on 5000, HMR host is `0.0.0.0` and the npm start script also uses this host `"start": "sirv public --host 0.0.0.0"`. When I change the HMR host to `127.0.0.1` the result is the same.

rollup.config.js
```javascript

import svelte from "rollup-plugin-svelte-hot";
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import livereload from "rollup-plugin-livereload";
import { terser } from "rollup-plugin-terser";
import hmr from "rollup-plugin-hot";

import fs from "fs";

// Set this to true to pass the --single flag to sirv (this serves your
// index.html for any unmatched route, which is a requirement for SPA
// routers using History API / pushState)
//
// NOTE This will have no effect when running with Nollup. For Nollup, you'd
// have to add the --history-api-fallback yourself in your package.json
// scripts (see: https://github.com/PepsRyuu/nollup/#nollup-options)
//
const spa = false;

// NOTE The NOLLUP env variable is picked by various HMR plugins to switch
// in compat mode. You should not change its name (and set the env variable
// yourself if you launch nollup with custom comands).
const nollup = !!process.env.NOLLUP;
const watch = !!process.env.ROLLUP_WATCH;
const useLiveReload = !!process.env.LIVERELOAD;

const dev = watch || useLiveReload;
const production = !dev;

const hot = watch && !useLiveReload;

export default {
  input: "src/main.js",
  output: {
    sourcemap: true,
    format: "iife",
    name: "app",
    file: "public/build/bundle.js",
  },
  plugins: [
    svelte({
      // Enable run-time checks when not in production
      dev: !production,
      // We'll extract any component CSS out into a separate file — better for
      // performance
      // NOTE when hot option is enabled, this gets automatically be turned to
      // false because CSS extraction doesn't work with HMR currently
      css: (css) => {
        css.write("public/build/bundle.css");
      },
      hot: hot && {
        // Optimistic will try to recover from runtime
        // errors during component init
        optimistic: true,
        // Turn on to disable preservation of local component
        // state -- i.e. non exported `let` variables
        noPreserveState: true,

        // See docs of rollup-plugin-svelte-hot for all available options:
        //
        // https://github.com/rixo/rollup-plugin-svelte-hot#usage
      },
    }),

    // If you have external dependencies installed from
    // npm, you'll most likely need these plugins. In
    // some cases you'll need additional configuration —
    // consult the documentation for details:
    // https://github.com/rollup/rollup-plugin-commonjs
    resolve({
      browser: true,
      dedupe: ["svelte"],
    }),
    commonjs(),

    // In dev mode, call `npm run start:dev` once
    // the bundle has been generated
    dev && !nollup && serve(),

    // Watch the `public` directory and refresh the
    // browser on changes when not in production
    // useLiveReload && livereload("public"),

    useLiveReload &&
      livereload({
        watch: "public",
        https: {
          key: fs.readFileSync(
            "/shared/httpd/devilbox/ca/certs/mass/svelte-hmr.loc.key"
          ),

          cert: fs.readFileSync(
            "/shared/httpd/devilbox/ca/certs/mass/svelte-hmr.loc.crt"
          ),
        },
      }),

    // If we're building for production (npm run build
    // instead of npm run dev), minify
    production && terser(),

    hmr({
      public: "public",
      inMemory: true,

      // Default host for the HMR server is localhost, change this option if
      // you want to serve over the network
      host: "0.0.0.0",
      // You can also change the default HMR server port, if you fancy
      // port: "12345",

      // This is needed, otherwise Terser (in npm run build) chokes
      // on import.meta. With this option, the plugin will replace
      // import.meta.hot in your code with module.hot, and will do
      // nothing else.
      compatModuleHot: !hot,
    }),
  ],
  watch: {
    clearScreen: false,
    // skipWrite: true,
  },
};

function serve() {
  let started = false;
  return {
    name: "svelte/template:serve",
    writeBundle() {
      if (!started) {
        started = true;
        const flags = ["run", "start", "--", "--dev"];
        if (spa) {
          flags.push("--single");
        }
        require("child_process").spawn("npm", flags, {
          stdio: ["ignore", "inherit", "inherit"],
          shell: true,
        });
      }
    },
  };
}
```
Using LiveReload all works fine on the secure local domain and on localhost and preserving local state or not.

```javascript
                var ws;

                if (typeof WebSocket === 'function') {
                    var protocol =  __nollup__global__.location.protocol === 'https:' ? 'wss://' : 'ws://';
                    ws = new WebSocket(protocol + __nollup__global__.location.host + '/__hmr');
                }
```
Have you got any idea or pointers why the HRM server started with Nollup does not work on a secure local domain?

**Comment by robots4life** [comment]
![Screenshot_20200828_155134](https://user-images.githubusercontent.com/34193243/91570634-6766e300-e946-11ea-8ec3-34f8e6e85559.png)
The scheme differs so perhaps that causes the issue on secure local domain? Given the above WebSocket it does support `https` and `wss` though.

**Comment by robots4life** [comment]
It looks like the Nollup Dev Server [supports](https://github.com/PepsRyuu/nollup/blob/HEAD/docs/dev-server.md) `https`, `key` and `crt`. Could you tell me more about what server, Rollup (does it have a dev server? docs?) or Nollup and the HMR feature is using?

**Comment by rixo** [comment]
Rollup doesn't have a dev server built in, or officially supported.

This plugin is intended to work either with rollup-plugin-hot, that adds a dev server with HMR support to Rollup, or with Nollup. It is tested against both of those options.

In my own projects, I usually setup both. I prefer Nollup's speed, but there are some rare situations where debugging is easier with Rollup's build. You can check my svelte-template-hot for an example of this mixed setup.

**Comment by robots4life** [comment]
> Rollup doesn't have a dev server built in, or officially supported.
> 
> This plugin is intended to work either with rollup-plugin-hot, that adds a dev server with HMR support to Rollup, or with Nollup. It is tested against both of those options.

Where can I find the docs for this added dev server with HRM support that comes with rollup-plugin-hot given the one for Nollup is this one [here](https://github.com/PepsRyuu/nollup/blob/HEAD/docs/dev-server.md)? Looking for how I could add `https`, `key` and `cert` somewhere and see what the default port is.

Going to check your [svelte-template-hot](https://github.com/rixo/svelte-template-hot) and see if I can get some https with a local domain going.

**Comment by robots4life** [comment]
The server that comes with rollup-plugin-hot is a Node server.

Looking at the documentation of [`https.createServer`](https://nodejs.org/dist/latest-v12.x/docs/api/https.html#https_https_createserver_options_requestlistener) I added an option object to your [`server.js`](https://github.com/rixo/rollup-plugin-hot/blob/master/lib/server.js#L73) passing the `key` and `cert` properties alongside the location of the certs. For this the `https` and `fs` modules are required.

```javascript

// require https and fs modules at top
const https = require('https');
const fs = require('fs');

// replace https://github.com/rixo/rollup-plugin-hot/blob/master/lib/server.js#L73 with this
// make sure to get the location of your cert right, could also be in same directory

  const options = {
    key: fs.readFileSync('/shared/httpd/devilbox/ca/certs/mass/svelte-hmr.loc.key'),
    cert: fs.readFileSync('/shared/httpd/devilbox/ca/certs/mass/svelte-hmr.loc.crt')
  };

  const server = https.createServer(options, app)
``` 
With this in place and running `npm run dev:rollup` while having

```javascript

    hmr({
      public: "public",
      inMemory: true,

      // Default host for the HMR server is localhost, change this option if
      // you want to serve over the network
      host: "0.0.0.0",
      // You can also change the default HMR server port, if you fancy
      // port: "334400",

      // This is needed, otherwise Terser (in npm run build) chokes
      // on import.meta. With this option, the plugin will replace
      // import.meta.hot in your code with module.hot, and will do
      // nothing else.
      compatModuleHot: !hot,
    }),
```
in `rollup.config.js` the script `/runtime/hmr-runtime.js` will not be served over `http` but over `https` and like this can be loaded.

Simply creating a `http` server also means that all files will be served over `http` and anything that is requested from the `https` to the `http` protocol will get a mixed content warning and hence not be loaded.

However now that `https://svelte-hmr.loc:33440/runtime/hmr-runtime.js` is indeed served over `https` it all works rather nice and super fast on a secure local development domain. :rocket: :muscle: 

![Screenshot_20200901_184052](https://user-images.githubusercontent.com/34193243/91883438-b84b4400-ec84-11ea-8881-3e44f1f93915.png)

![Screenshot_20200901_203919](https://user-images.githubusercontent.com/34193243/91892708-6d84f880-ec93-11ea-89b0-acb9d93efb59.png)

Two things that come from this.

You could add an option to your plugin to make a https server and pass the `key` and `cert` properties from the `rollup.config.js` file to the server. Like this people that want to use http2 or https on their secure local development domain can do so.

You could have a look at how Nollup goes about it, as there the websocket `__hmr` cannot be found, possibly as well due to the socket running on `wss` but the Nollup dev server is using `http` so perhaps does not support `wss`. However looking at their docs and passing
```
"dev:nollup": "nollup -c --verbose --host 0.0.0.0 --https --cert /shared/httpd/devilbox/ca/certs/mass/svelte-hmr.loc.crt --key /shared/httpd/devilbox/ca/certs/mass/svelte-hmr.loc.key --hot --port 5000 --content-base ./public",
```
does not affect the socket. However I might have the syntax wrong plus I have not taken the time to use https://github.com/PepsRyuu/nollup/blob/38669853c30395f12f88d98a1dc18e926f652d50/docs/nolluprc.md and do the Nollup dev server config with that. Might be worth a shot though.

![Screenshot_20200901_185333](https://user-images.githubusercontent.com/34193243/91883567-e6c91f00-ec84-11ea-85f1-d0219d28b833.png)

```javascript
ws = new WebSocket(protocol + __nollup__global__.location.host + '/__hmr');
```

Like I said before the functionality of https://github.com/rixo/svelte-hmr#preservation-of-local-state and added HMR support always worked fine on `http` and with the little addition above I managed to get this going on `https` as well. :smile: :tada:

**Comment by rixo** [comment]
I guess we're done here, so closing. Feel free to open a new issue if there's something I've missed in the discussion above.

**Comment by robots4life** [comment]
The only thing I am missing is an SSL / HTTPS option in your plugin. I would like to be able to have the underlying Node server accept my certs and work with the HTTPS protocol without having to change your `server.js` file in the plugin.

Would you kindly be able to include a condition in your `server.js` to check for a chosen https option in `rollup.config.js` that provides the certs, if this option has values then the certs are passed and the Node server runs on HTTPS.

In the `rollup.config.js` under `hrm` one could then provide those certs similar like is done with LiveReload.

```javascript
hmr({
    public: "public",
    inMemory: true,

    // Default host for the HMR server is localhost, change this option if
    // you want to serve over the network
    host: "0.0.0.0",
    // You can also change the default HMR server port, if you fancy
    // port: "334400",

    https: {
        key: fs.readFileSync(
            '/shared/httpd/devilbox/ca/certs/mass/YOUR_PROJECT_DOMAIN_FOLDER.loc.key',
        ),

        cert: fs.readFileSync(
            '/shared/httpd/devilbox/ca/certs/mass/YOUR_PROJECT_DOMAIN_FOLDER.loc.crt',
        ),
    },

    // This is needed, otherwise Terser (in npm run build) chokes
    // on import.meta. With this option, the plugin will replace
    // import.meta.hot in your code with module.hot, and will do
    // nothing else.
    compatModuleHot: !hot,
  }),
```
Do you think you could kindly add this feature?

**Comment by rixo** [comment]
Yes, makes sense to me. I'll add that to rollup-plugin-hot. You can submit a PR if you want to speed up the process.

**Comment by robots4life** [comment]
I would love to make a PR. :heart:
How can I pass values from or check for values in `rollup.plugin.js` to `server.js` please?
In pseudo code in `server.js` I'd like to have something along the lines of this.

```
if hmr server option (in rollup.config.js) is https then use key and cert ((in rollup.config.js)
else const server = http.createServer(app)
```

My issue is that I don't know how to check for options given to `hmr` in the `rollup.config.js` file.
Could you let me know how that work or link me to a tut that will enable me to provide a PR?

**Comment by robots4life** [comment]
With Hacktoberfest coming up this could become my first ever PR even. I already tried to access values in `rollup.config.js` inside the `server.js` file but whatever I try, import export etc. does not get the values needed. So yeah, would be quite happy to learn this and then submit a PR with your help, given you have a bit of time to spare.

**Comment by rixo** [comment]
Sure.

Node entry point (that is, the Rollup plugin) is [index.js](https://github.com/rixo/rollup-plugin-hot/blob/6fcc2ecaab39fcba3788fd23fc99153ab2df5ad9/package.json#L4).

That's what you get when you `import hmr from 'rollup-plugin-hot'`. Said otherwise, that's the function that receives the argument that you want to check for `https` option.

```js
hmr({
   ...options,
   https: { ... },
})
```

This function actually comes from [`lib/hmr`](https://github.com/rixo/rollup-plugin-hot/blob/6fcc2ecaab39fcba3788fd23fc99153ab2df5ad9/index.js#L3).

So, [here](https://github.com/rixo/rollup-plugin-hot/blob/6fcc2ecaab39fcba3788fd23fc99153ab2df5ad9/lib/hmr.js#L161)'s where you get the options passed to the plugin from Rollup config. Get `https` option from here.

Server options are then passed [here](https://github.com/rixo/rollup-plugin-hot/blob/6fcc2ecaab39fcba3788fd23fc99153ab2df5ad9/lib/hmr.js#L230). Pass `https` option here.

Then, finally, you'll get it [here](https://github.com/rixo/rollup-plugin-hot/blob/6fcc2ecaab39fcba3788fd23fc99153ab2df5ad9/lib/server.js#L52).

I think that's the scope where you need the option so you should be able to pick up from here.

Maybe create a draft PR or an issue about https in `rollup-plugin-hot` to continue this discussion. Feel free if you have any follow-up questions...

**Comment by robots4life** [comment]
**Thank you so much!** I will get to work and report back, kindly excuse me if this takes a bit of time since I am doing this the first time. If you like we can close this ticket but keep working on it until the draft PR is done. Would that suit you? Otherwise happy to keep it open until all is done. As you prefer. Super excited to learn this. :100:

**Comment by rixo** [comment]
No problem, I'm snowed under work on my side too, so slow motion fits me very well :)

So... This issue has already been closed for 7 days already ;) It would be better to move the discussion to the relevant project (rollup-plugin-hot), in something open. I think the best would be a draft PR to keep everything in one place, but an issue can also do for now (I don't know too much if / how you can create an empty PR / draft PR).

So, do as you see fit, open a PR or issue in the other project, and I'll meet you there!

**Comment by robots4life** [comment]
:+1:

**Comment by rixo** [comment]
@robots4life You should check [this PR](https://github.com/rixo/rollup-plugin-hot/pull/12/files). It's making something very similar to what you want, adding an option to the plugin and then applying it in server.js.

**Comment by robots4life** [comment]
Great, thank you, will go over that.

**Comment by robots4life** [comment]
@rixo I am still learning this and found someone to guide me through this, kindly don't mind the delay or the time this takes, I am on this and have not forgotten this. Thank you.

**Comment by rixo** [comment]
Thanks for the update. No problem, I'm not your boss, take your own time. You're welcome if you have any question or need some help on something.
